// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfviydzxgalogzzbvzzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmdml5ZHp4Z2Fsb2d6emJ2enp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODY3ODgsImV4cCI6MjA3MzM2Mjc4OH0.dJ3f1YxEdg-ZiJGol4BE8UmcOXTrjIQDKxcH5e6GFhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});